"""Canonical model-lane and provider-route metadata for adaptive orchestration."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

_CANONICAL_MODEL_LANES: dict[str, dict[str, Any]] = {
    "anthropic/opus-4.6": {
        "family": "anthropic",
        "name": "quality",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["anthropic/sonnet-4.6", "openai/gpt-4o", "deepseek/reasoner"],
        "last_reviewed": "2026-03-22",
    },
    "anthropic/sonnet-4.6": {
        "family": "anthropic",
        "name": "workhorse",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai/gpt-4o", "google/gemini-pro-high"],
        "last_reviewed": "2026-03-22",
    },
    "anthropic/haiku-4.5": {
        "family": "anthropic",
        "name": "fast",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash", "openai/gpt-4o-mini"],
        "last_reviewed": "2026-03-22",
    },
    "google/gemini-pro-high": {
        "family": "google",
        "name": "quality",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-pro-low", "google/gemini-flash"],
        "last_reviewed": "2026-03-22",
    },
    "google/gemini-pro-low": {
        "family": "google",
        "name": "balanced",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-03-22",
    },
    "google/gemini-flash": {
        "family": "google",
        "name": "fast",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash-lite", "deepseek/chat"],
        "last_reviewed": "2026-03-22",
    },
    "google/gemini-flash-lite": {
        "family": "google",
        "name": "cheap",
        "cluster": "budget-general",
        "benchmark_cluster": "budget-chat",
        "quality_tier": "budget",
        "reasoning_strength": "low",
        "context_strength": "mid",
        "tool_strength": "low",
        "preferred_degrades": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
        "last_reviewed": "2026-03-22",
    },
    "openai/gpt-4o": {
        "family": "openai",
        "name": "balanced",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["openai/gpt-4o-mini", "google/gemini-pro-high"],
        "last_reviewed": "2026-03-22",
    },
    "openai/gpt-4o-mini": {
        "family": "openai",
        "name": "fast",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "mid",
        "preferred_degrades": ["google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-03-22",
    },
    "openai/gpt-image-1": {
        "family": "openai",
        "name": "image",
        "cluster": "image-quality",
        "benchmark_cluster": "image-generation",
        "quality_tier": "premium",
        "reasoning_strength": "n/a",
        "context_strength": "n/a",
        "tool_strength": "n/a",
        "preferred_degrades": [],
        "last_reviewed": "2026-03-22",
    },
    "deepseek/reasoner": {
        "family": "deepseek",
        "name": "reasoning",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "reasoning-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["deepseek/chat", "google/gemini-pro-high"],
        "last_reviewed": "2026-03-22",
    },
    "deepseek/chat": {
        "family": "deepseek",
        "name": "workhorse",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash", "aggregator/openrouter-auto"],
        "last_reviewed": "2026-03-22",
    },
    "aggregator/openrouter-auto": {
        "family": "openrouter",
        "name": "router",
        "cluster": "aggregator-fallback",
        "benchmark_cluster": "marketplace-general",
        "quality_tier": "variable",
        "reasoning_strength": "variable",
        "context_strength": "variable",
        "tool_strength": "variable",
        "preferred_degrades": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
        "last_reviewed": "2026-03-22",
    },
    "aggregator/kilo-glm5-free": {
        "family": "kilo",
        "name": "free",
        "cluster": "budget-general",
        "benchmark_cluster": "free-coding",
        "quality_tier": "free",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "low",
        "preferred_degrades": ["aggregator/blackbox-grok-code-fast", "google/gemini-flash-lite"],
        "last_reviewed": "2026-03-22",
    },
    "aggregator/blackbox-grok-code-fast": {
        "family": "blackbox",
        "name": "free-burst",
        "cluster": "budget-general",
        "benchmark_cluster": "free-coding",
        "quality_tier": "free",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "mid",
        "preferred_degrades": ["aggregator/kilo-glm5-free", "google/gemini-flash-lite"],
        "last_reviewed": "2026-03-22",
    },
}

_PROVIDER_LANE_BINDINGS: dict[str, dict[str, Any]] = {
    "anthropic-claude": {
        "family": "anthropic",
        "name": "quality",
        "canonical_model": "anthropic/opus-4.6",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "anthropic/opus-4.6",
        "degrade_to": ["anthropic/sonnet-4.6", "openai/gpt-4o", "deepseek/reasoner"],
    },
    "deepseek-chat": {
        "family": "deepseek",
        "name": "workhorse",
        "canonical_model": "deepseek/chat",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "deepseek/chat",
        "degrade_to": ["google/gemini-flash", "aggregator/openrouter-auto"],
    },
    "deepseek-reasoner": {
        "family": "deepseek",
        "name": "reasoning",
        "canonical_model": "deepseek/reasoner",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "reasoning-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "deepseek/reasoner",
        "degrade_to": ["deepseek/chat", "google/gemini-pro-high"],
    },
    "gemini-flash": {
        "family": "google",
        "name": "fast",
        "canonical_model": "google/gemini-flash",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "google/gemini-flash",
        "degrade_to": ["google/gemini-flash-lite", "deepseek/chat"],
    },
    "gemini-flash-lite": {
        "family": "google",
        "name": "cheap",
        "canonical_model": "google/gemini-flash-lite",
        "route_type": "direct",
        "cluster": "budget-general",
        "benchmark_cluster": "budget-chat",
        "quality_tier": "budget",
        "reasoning_strength": "low",
        "context_strength": "mid",
        "tool_strength": "low",
        "same_model_group": "google/gemini-flash-lite",
        "degrade_to": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
    },
    "openai-gpt4o": {
        "family": "openai",
        "name": "balanced",
        "canonical_model": "openai/gpt-4o",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "openai/gpt-4o",
        "degrade_to": ["openai/gpt-4o-mini", "google/gemini-pro-high"],
    },
    "openai-images": {
        "family": "openai",
        "name": "image",
        "canonical_model": "openai/gpt-image-1",
        "route_type": "direct",
        "cluster": "image-quality",
        "benchmark_cluster": "image-generation",
        "quality_tier": "premium",
        "reasoning_strength": "n/a",
        "context_strength": "n/a",
        "tool_strength": "n/a",
        "same_model_group": "openai/gpt-image-1",
        "degrade_to": [],
    },
    "openrouter-fallback": {
        "family": "openrouter",
        "name": "router",
        "canonical_model": "aggregator/openrouter-auto",
        "route_type": "aggregator",
        "cluster": "aggregator-fallback",
        "benchmark_cluster": "marketplace-general",
        "quality_tier": "variable",
        "reasoning_strength": "variable",
        "context_strength": "variable",
        "tool_strength": "variable",
        "same_model_group": "aggregator/openrouter-auto",
        "degrade_to": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
    },
    "kilocode": {
        "family": "kilo",
        "name": "free",
        "canonical_model": "aggregator/kilo-glm5-free",
        "route_type": "aggregator",
        "cluster": "budget-general",
        "benchmark_cluster": "free-coding",
        "quality_tier": "free",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "low",
        "same_model_group": "aggregator/kilo-glm5-free",
        "degrade_to": ["aggregator/blackbox-grok-code-fast", "google/gemini-flash-lite"],
    },
    "blackbox-free": {
        "family": "blackbox",
        "name": "free-burst",
        "canonical_model": "aggregator/blackbox-grok-code-fast",
        "route_type": "aggregator",
        "cluster": "budget-general",
        "benchmark_cluster": "free-coding",
        "quality_tier": "free",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "mid",
        "same_model_group": "aggregator/blackbox-grok-code-fast",
        "degrade_to": ["aggregator/kilo-glm5-free", "google/gemini-flash-lite"],
    },
    "clawrouter": {
        "family": "blockrun",
        "name": "wallet-router",
        "canonical_model": "aggregator/openrouter-auto",
        "route_type": "wallet-router",
        "cluster": "aggregator-fallback",
        "benchmark_cluster": "marketplace-general",
        "quality_tier": "variable",
        "reasoning_strength": "variable",
        "context_strength": "variable",
        "tool_strength": "variable",
        "same_model_group": "aggregator/openrouter-auto",
        "degrade_to": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
    },
}


def get_canonical_model_catalog() -> dict[str, dict[str, Any]]:
    """Return the canonical model-lane catalog."""
    return deepcopy(_CANONICAL_MODEL_LANES)


def get_provider_lane_binding(provider_name: str) -> dict[str, Any]:
    """Return lane metadata for one configured provider or route."""
    binding = _PROVIDER_LANE_BINDINGS.get(provider_name, {})
    return deepcopy(binding)
